---
services: docker

env:
  # Test package install on all supported OSes.
  - distro: centos6
    init: /sbin/init
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
  - distro: debian8
    init: /sbin/initctl
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
  - distro: ubuntu1404
    init: /sbin/init
    run_opts: ""
    playbook: test.yml
  - distro: ubuntu1204
    init: /sbin/init
    run_opts: ""
    playbook: test.yml

before_install:
  # Pull container.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)
  # Run playbook in container
  - 'docker run --tty --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest  env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} -vvv> "${container_id}"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
